apiVersion: v1
kind: Service
metadata:
    name: nayeemhbuethackathonfrontend
spec:
    type: LoadBalancer
    ports:
    - port: 4200 
    selector:
        app: nayeemhbuethackathonfrontend